### ISSUE TITLE
mmorpg分服

### ISSUE THREAD

**Issue by xliangzy** [zhandouxiaojiji/bewater#4]
想请教下，运营有分区分服的需求。一般来说，是一个服一个skynet进程，还是说一台机只有一个skynet进程，多个服在同一个进程。如果后者的话，如果能较好地隔离开。

**Comment by zhandouxiaojiji** [comment]
我看到多数人的做法都是，中心服一个进程，然后多个游戏服放到同一个进程，如果单台机器支撑不住，再加机器。个人不建议一个服一个进程，这样对滚服合服之类的运维操作不太友好。

至于如何隔离，我不是很清楚你的意思，首先服务本身就是lua虚拟机，它已经做了很好的隔离。如果你说的是逻辑上的隔离，那你可以把游戏服的逻辑通通写到服务内，然后服务写成目录的形式，本目录下的所有脚本都只有本服务才能require。而lualib里的库只放一些很通用的方法，最好是类似纯函数那种，这样服务间的逻辑就不容易混淆了。

**Comment by xliangzy** [comment]
我想问的是逻辑上面的隔离。比方说，我有个仙盟的服务。如果防止别的服的玩家串到别的服的仙盟上面去。如果说，一个服对应有一个仙盟服务，如果能更好地管理好，自己服的玩家只会访问到自己服的仙盟服务

**Comment by zhandouxiaojiji** [comment]
游戏服的主服务应当在创建子服务的时候，把各种系统的服务地址记录下来，同它来统一管理。

当然还有一种比较笨的办法就是给系统的服务起名的时候加上游戏服的编号，xianmen001, xianmen002。。。

**Comment by xliangzy** [comment]
中心服一般是用来处理什么业务的。

**Comment by zhandouxiaojiji** [comment]
管理游戏服，玩家登录token，GM入口，对接后台之类的

**Comment by xliangzy** [comment]
好的，非常感谢！
