### ISSUE TITLE
请问考虑提供一个watchdog agent模式的示例吗？

### ISSUE THREAD

**Issue by mikewu86** [zhandouxiaojiji/bewater#6]
你好，websocket使用，请问考虑提供一个watchdog agent模式的示例吗？

**Comment by hanxi** [comment]
可以参考 simplewebsocket.lua 写一个

**Comment by mikewu86** [comment]
嗯呢，跑起来了也调通了，我是想每个玩家都拥有一个独立的agent，然而forward看得有点懵

**Comment by hanxi** [comment]
一个玩家一个agent可以不用forward，直接socket.start那里传空的agent进去就行了。

**Comment by zhandouxiaojiji** [comment]
近期会把ws加到示例中，一个玩家一个agent有点奢侈，哈哈

**Comment by hanxi** [comment]
```lua
socket.start(id, function(id, addr)
            print(string.format("accept client socket_id: %s addr:%s", id, addr))
            local free_agent = get_free_agent()
            skynet.send(free_agent, "lua", id, protocol, addr)
            balance = balance + 1
            if balance > #agent then
                balance = 1
            end
end)
```

**Comment by hanxi** [comment]
@zhandouxiaojiji 弄个开房间的那种示例吧，开房间那种才会用到 forward

**Comment by mikewu86** [comment]
了解。在消息收发那里用redirect把消息投递过去是吗？

**Comment by zhandouxiaojiji** [comment]
@hanxi 可以，近期正打算做个需要开房间的小游戏

**Comment by hanxi** [comment]
https://github.com/xzhovo/skynet-websocket-gate

找到个例子

**Comment by hanxi** [comment]
我参考上面那个写了个  https://github.com/hanxi/skynet-demo/blob/master/service/ws_gate.lua
