### ISSUE TITLE
支持mac吗

### ISSUE THREAD

**Issue by semgilo** [zhandouxiaojiji/bewater#7]
支持mac吗

**Comment by zhandouxiaojiji** [comment]
没编译过

**Comment by semgilo** [comment]
你们的开发环境直接就是linux下的吗？

**Comment by semgilo** [comment]
顺便问下 新版的skynet的协程还需要协程锁？感觉这样子用起来心里没什么底

**Comment by zhandouxiaojiji** [comment]
看个人喜好吧，我在mac上也是直连服务器或虚拟机开发的。

协程锁跟skynet.coroutine那个协程没啥关系，协程锁只是为了防重入，就是在防止在服务在处理消息的时候wait或者call出去，在回调到来之前，又有别的消息到来，而重复执行某一个代码块，比如id分配服务。使用协程锁存在一定的风险，最好在设计上让代码可重入，规避协程锁的使用。

**Comment by semgilo** [comment]
好的 非常感谢解答
